#
# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2013-2023 Igor Pecovnik, igor@armbian.com
#
# This file is a part of the Armbian Build Framework
# https://github.com/armbian/build/
#
CPUMIN=100000
CPUMAX=2508000
GOVERNOR=performance # conservative powersave performance schedutil

ARCH=arm64
BOOTSCRIPT="boot-meson64.cmd:boot.cmd"
BOOTENV_FILE='meson.txt'
BOOTSOURCE="https://git.odroid.com/yocto/uboot"
BOOTBRANCH="branch:odroidc5-v2023.01"
BOOTPATCHDIR="u-boot-meson-s7d"
BOOT_FDT_DIR="amlogic/s7d_s905x5m_odroidc5.dtb"
UBOOT_TARGET_MAP="u-boot-nodtb.bin"
PRE_CONFIG_UBOOT_TARGET="no"
POST_CONFIG_UBOOT_TARGET="no"

KERNELSOURCE="https://github.com/hardkernel/linux.git"
KERNELBRANCH="branch:odroids7d-5.15.y"
KERNELPATCHDIR="meson-s7d-legacy"
KERNEL_MAJOR_MINOR="5.15"
EXTRAWIFI="no"

# this family does not need it
ATF_COMPILE="no"

# We'll need crc32 and xxd to build the final uboot
function add_host_dependencies__uboot_needs_odroidc5() {
	display_alert "Adding libarchive-zip-perl and xxd to host dependencies" "for ODroid C5 bootloader compile" "debug"
	declare -g EXTRA_BUILD_DEPS="${EXTRA_BUILD_DEPS} libarchive-zip-perl xxd"
}

family_tweaks() {
	:
}

# TODO - Push ODroid C5 FIP stuff upstream
function fetch_sources_tools__libreelec_amlogic_fip_odroidc5() {
	fetch_from_repo "https://github.com/tparys/amlogic-boot-fip" "amlogic-boot-fip" "branch:odroid-c5"
}

compile_uboot_target() {

	declare cross_compile="undetermined_cross_compile"
	if [[ -n "${CCACHE}" ]]; then
		cross_compile="CROSS_COMPILE='${CCACHE} ${UBOOT_COMPILER}'"
	else
		cross_compile="CROSS_COMPILE='${UBOOT_COMPILER}'"
	fi

	# Compile uboot target
	for TARGET in mrproper "${BOOTCONFIG}" "${UBOOT_TARGET_MAP[@]}"; do
		run_host_command_logged CCACHE_BASEDIR="$(pwd)" \
			pipetty make "${CTHREADS}" "${cross_compile}"
	done

	# TODO - Break S7D post-process into separate function?
	local uboot_in="${PWD}/build/u-boot-nodtb.bin"
	local uboot_build="${PWD}/build"
	local uboot_out="${uboottempdir}/usr/lib/linux-u-boot-legacy-odroidc5"
	pushd "$SRC"/cache/sources/amlogic-boot-fip/odroid-c5
	make BL33="${uboot_in}" TMP="${uboot_build}" O="${uboot_out}"
	popd
	mv "${uboot_out}/u-boot.bin"{.signed,}
}

write_uboot_platform() {
	dd if=$1/u-boot.bin of=$2 conv=fsync seek=1 2>&1
}
