#
# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2013-2023 Igor Pecovnik, igor@armbian.com
#
# This file is a part of the Armbian Build Framework
# https://github.com/armbian/build/
#
CPUMIN=100000
CPUMAX=2508000
GOVERNOR=performance # conservative powersave performance schedutil

BOOTSOURCE="https://git.odroid.com/yocto/uboot"
BOOTBRANCH="branch:odroidc5-v2023.01"
BOOTPATCHDIR="u-boot-meson-s7d"
BOOT_FDT_DIR="amlogic/s7d_s905x5m_odroidc5.dtb"
UBOOT_TARGET_MAP=";u-boot-nodtb.bin"
PRE_CONFIG_UBOOT_TARGET="no"
POST_CONFIG_UBOOT_TARGET="no"

KERNELSOURCE="https://github.com/hardkernel/linux.git"
KERNELBRANCH="branch:odroids7d-5.15.y"
KERNELPATCHDIR="meson-s7d-legacy"
KERNEL_MAJOR_MINOR="5.15"
EXTRAWIFI="no"

# this family does not need it
ATF_COMPILE="no"

# We'll need xxd to build the fip blobs
function add_host_dependencies__uboot_needs_crc32() {
	display_alert "Adding libarchive-zip-perl to host dependencies" "for ODroid C5 bootloader compile" "debug"
	declare -g EXTRA_BUILD_DEPS="${EXTRA_BUILD_DEPS} libarchive-zip-perl"
}

family_tweaks() {
	:
}

function fetch_sources_tools__libreelec_amlogic_fip_odroidc5() {
	fetch_from_repo "https://github.com/tparys/amlogic-boot-fip" "amlogic-boot-fip" "branch:odroid-c5"
}

compile_uboot_target() {

	declare cross_compile="undetermined_cross_compile"
	if [[ -n "${CCACHE}" ]]; then
		cross_compile="CROSS_COMPILE='${CCACHE} ${UBOOT_COMPILER}'"
	else
		cross_compile="CROSS_COMPILE='${UBOOT_COMPILER}'"
	fi

	run_host_command_logged CCACHE_BASEDIR="$(pwd)" \
		pipetty make "${CTHREADS}" "${BOOTCONFIG}" "${cross_compile}"

	run_host_command_logged CCACHE_BASEDIR="$(pwd)" \
		pipetty make "${CTHREADS}" "${cross_compile}"
}

write_uboot_platform() {
	dd if=$1/u-boot.bin of=$2 conv=fsync seek=1 2>&1
}
