#
# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2013-2023 Igor Pecovnik, igor@armbian.com
#
# This file is a part of the Armbian Build Framework
# https://github.com/armbian/build/
#
CPUMIN=100000
CPUMAX=2508000
GOVERNOR=performance # conservative powersave performance schedutil

BOOTSOURCE="https://git.odroid.com/yocto/uboot"
BOOTBRANCH="branch:odroidc5-v2023.01"
BOOTPATCHDIR="legacy"
BOOT_FDT_DIR="amlogic/s7d_s905x5m_odroidc5.dtb"

KERNELSOURCE="https://github.com/hardkernel/linux.git"
KERNELBRANCH="branch:odroids7d-5.15.y"
KERNELPATHDIR="meson-s7d-legacy"
KERNEL_MAJOR_MINOR="5.15"

# this family does not need it
ATF_COMPILE="no"

family_tweaks() {
	:
}

function fetch_sources_tools__libreelec_amlogic_fip_odroidc5() {
	fetch_from_repo "https://github.com/tparys/amlogic-boot-fip" "amlogic-boot-fip" "branch:odroid-c5"
}

write_uboot_platform() {
	dd if=$1/u-boot.bin of=$2 conv=fsync seek=1 2>&1
}
